version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: change into the frontend dir
          command: cd frontend
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Build frontend
          command: npm build
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: change into the backend dir
          command: cd backend
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Build frontend
          command: npm build

workflows:
  defaults:
    jobs:
      - build-frontend
      - build-backend
