- name: Update all Packages
  become: true
  apt: name=* state=latest

- name: Install python
  become: true
  apt: name=python3 state=present

- name: Install nodejs
  become: true
  run: curl -fsSL https://deb.nodesource.com/setup_16.x |sudo -E bash
  apt: name=nodejs state=present

- name: Install npm
  become: true
  apt: name=npm state=present

- name: Install pm2
  become: true
  npm: name=pm2 state=present
